import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import Marquee from "@/components/Marquee";
import ScrollProvider from "./ScrollProvider";

// Import Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Include the font weights you need
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const items = [
//   "Get In Touch",
//   "Get In Touch",
//   "Get In Touch",
//   "Get In Touch",
//   "Get In Touch",
//   "Get In Touch",
//   "Get In Touch",
// ];

const items2 = [
  "Contact Us",
  "Contact Us",
  "Contact Us",
  "Contact Us",
  "Contact Us",
  "Contact Us",
  "Contact Us",
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-[#0D0D0D] ${poppins.className}`}
        suppressHydrationWarning
      >
        <ScrollProvider>
          <div className="border-1 border-transparent relative bg-gradient-to-b from-[#0D0D0D] to-[#161616]">

          <div className="absolute top-0 right-0 w-[60vw] h-[70vh] bg-gradient-to-br from-[#FF5513] via-transparent to-transparent rounded-full blur-3xl opacity-60 z-0" />
          <div className="absolute bottom-0 left-0 w-[60vw] h-[70vh] bg-gradient-to-tl from-[#FF5513] via-transparent to-transparent rounded-full blur-3xl opacity-60 z-0" />
          <Header />
          {children}
            {/* <Marquee
              items={items}
              className=""
              itemClassName="marquee-item"
              direction="backward"
            /> */}

            {/* Bottom-to-top diagonal (forward) */}
            <Marquee
              items={items2}
              className="marquee-bg rotate-[5deg]"
              itemClassName="marquee-item"
              // direction="forward"
            />
          <Footer />
        </div>
        </ScrollProvider>
      </body>
    </html>
  );
}
